# Generated by Django 5.1.4 on 2024-12-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='memiliki_riwayat_penyakit_epilepsi_dan_atau_gangguan_saraf_lainnya',
            field=models.CharField(choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], db_column='riwayat_penyakit_epilepsi', max_length=5),
        ),
    ]
